.\" muh mans
.TH CALU 1 "17 Mar 2021" "0.1" "CALU man page"
.SH NAME
CALU \- char based arithmetic calculator 
.SH SYNOPSIS
.B CALU
expression

.B CALU
number[(op)number]
.SH DESCRIPTION
.B CALU
is an arithmetic calculator that works with string literal digits rather than actual integers, breaking the limit that integers have.
.SH EXAMPLES
In: 2+2          / Out: 4                // lol

In: 2147483647*2 / Out: 4294967294
.SH OPTIONS
Operators:

+ - / * % ^
.SH SEE ALSO
expr(1)
.SH BUGS
No known bugs.
.SH AUTHOR
donnaken15 / Wesley Kennedy (wesley@gmx.it)
